codeenigma/deployments

drupal/fabfile.py
This will run after all tests have been run.
=> New build hook executor

drupal/Revert.py
Cherry-picks the commit that entered develop branch already
=> Fix the database revert steps

drupal/fabfile.py
=> drush_fra missing argument

common/Utils.py, drupal/Drupal.py, drupal/Multisite.py, drupal/fabfile.py, symfony/fabfile.py
There is also a quick Symfony fix in here where buildtype was not being passed for path, which caused problems when running build hooks.
=> Moving multisite support into the main fabfile for Drupal

common/ConfigFile.py, drupal/Drupal.py, drupal/fabfile-multisite.py, drupal/fabfile.py
See #103 for details - my only concern here (aside from typos / missing something) is whether the FeatureBranches bit needs to come before or after the branchname clean-up (because of Gitflow).
=> Refactoring config handling so it's much easier to read

drupal/FeatureBranches.py
This is related to https://github.com/codeenigma/deployments/issues/120 but isn't a fix for it.
The change is to allow for the scenario where `drush status` returns non-zero but still outputs the `Database name` field successfully.
=> remove_site: don't fail on drush status fail

drupal/FeatureBranches.py, drupal/fabfile.py
As per #127, URL templates for feature branches does not currently work as expected. This is not a final fix, as I need to do some testing regarding the `url` variable.
=> FeatureBranch urltemplate fix

util/fabfile-sftp.py
This file will be used to copy files (not Drupal or website files) from one server to another, via a central Jenkins server.
=> Adding a fabfile-sftp.py script

drupal/fabfile.py
=> Forgot to add www_root to test_runner() wrapper function.

common/MySQL.py, drupal/Drupal.py, drupal/fabfile-drushcommand.py, drupal/fabfile-updates.py, drupal/fabfile.py
Does what it says on the tin! And fixes #86.
=> Making MySQL backups and restores common functionality

common/Composer.py, common/PHP.py, common/Utils.py, drupal/Drupal.py, drupal/fabfile-drushcommand.py, drupal/fabfile.py
Fixes #97 - composer commands moved to common functionality.
=> Abstracting composer functionality

common/Tests.py, symfony/Symfony.py, symfony/fabfile.py
Using common Composer functionality across the board.
=> Making changes to Symfony and testing scripts

common/Tests.py, drupal/fabfile-sync.py, drupal/fabfile.py
I think this is good to go straight to live and it closes #219!
=> New regex check, passed tests in 'develop'

common/PHP.py, drupal/fabfile.py
=> Composer commands through _sshagent_run()

drupal/Drupal.py
I've tested this on a client's build (I don't think I have my own build that actually runs features) and feature reverting does work.
=> Fix feature reverting

drupal/fabfile.py
Internal ticket reference: r45026
=> Clear opcache again after a site has been brought back online.

drupal/fabfile.py
And, if the phpunit tests fail and config.ini says to revert, revert the live symlink too as well as the db and settings.
=> Run phpunit tests before Behat tests 

drupal/fabfile.py
=> Add ability to revert the build or not when phpunit tests fail

drupal/Sync.py, drupal/fabfile-sync.py, drupal/fabfile.py
This has now been tested by a client too, so it should be safe to go through to the master scripts. :)
=> Drupal syncs

drupal/Drupal.py, drupal/DrupalUtils.py, drupal/Multisite.py
=> Use appropriate drush upwd command based on installed version of Drush

drupal/fabfile.py
Not entirely certain this is enough to make sure the default value is True.
=> r51578_initial_commit

symfony/Symfony.py, symfony/fabfile.py
Sessions are also on the NAS (fml) so actually, we're probably stuck doing most of this nonsense!
=> r40112 - making perms fixes more granular for performance.

symfony/fabfile.py
=> r54842 - trying to grab previous_build before hosts are defined.
