codeenigma/deployments

common/ConfigFile.py
drupal/fabfile.py

Adding a wrapper function to leave the standard config.ini in place but provide a route to support buildtype-specific config.ini files in the main fabfiles if we need to.

Supporting config.ini per buildtype as an option.

---

drupal/fabfile-multisite.py
drupal/fabfile.py
util/fabfile.py

Simple solution, I prefer this to detecting "vendor" in the repo, I don't think we should assume if "vendor" is present the developer doesn't want a `composer install` - ultimately we'll want this in config.ini, but a manual Jenkins flag for now is fine, I think.

Allowing us to bypass 'composer install'

---

drupal/fabfile.py

I think the post and post-initial build hooks should be run **before** Behat tests are run, as there could be hooks that affect Behat tests, such as moving a specific behat.yml file into place.
Also, some Behat tests can take *a long* time to run, so having the post build hooks run before the tests could be beneficial.

Run post-build and post-initial-build hooks before Behat tests run.

---

drupal/Drupal.py
drupal/fabfile.py

This is a suggested change to allow a wildcard to be used for the [Features] configuration option rather then having to explicitly name branches.
Also, added a check to make sure the the features module is actually installed before attempting a feature revert.

Allow wildcard for features and check that features module is installed

---

drupal/Sync.py

I know this was tidier as a one-liner, however it's handy to know how far Jenkins got by virtue of whether or not the db dump is still there on the Jenkins server - so this helps debug a little.

Moving when we delete db dump

---

common/Tests.py
drupal/fabfile.py

This closes a Composer possible bad behaviour where if you do not specify --no-dev it seems to allow dev components to be installed by default.

Making sure dev components are not installed by mistake

---

drupal/Drupal.py

I feel like I must be missing something here and I'm ready to be shot down, but as far as I can tell the drush_fra_branches code will always fail with `NameError: name 'branches' is not defined` because python won't allow a list to be appended to if it doesn't already exist.

drush_fra_branches: need to declare branches before appending to it

---

drupal/AdjustConfiguration.py

Fix is pretty self-explanatory, there were a couple of rogue parameters in there. This was enough to break a D7 build.

fix typeerror for D7

---

drupal/fabfile.py

We don't need to generate a URL in the initial_build_wrapper() function as it's already done before that function is called. If we do it in here, then the URL is going to be wrong for multisite sites. Also removing an erroneous space.

Remove extra URL generation

---

drupal/FeatureBranches.py
drupal/fabfile.py

Again for #127. I've reworked the variable that's used, as for some reason the global `url` variable couldn't be used.

More featurebranch url fixes

---

drupal/fabfile-multisite.py

Feature branches are used in fabfile-multisite.py, at the moment. Nor will they be in the future, as we'll move to the main fabfile.py script.

Comment out feature branch code 

---

drupal/FeatureBranches.py

A quick partial fix for https://github.com/codeenigma/deployments/issues/99 as some of our Teardowns started failing.
e.g.
```
run: drush sa | grep '^@\?REDACTED$' > /dev/null
sudo: drush status 2>&1 | grep "Database name " | cut -d ":" -f 2
DEBUG INFO: dbname = 
sudo: grep "'database' => 'REDACTED*" settings.php | cut -d ">" -f 2
sudo: mysql --defaults-file=/etc/mysql/debian.cnf -e 'DROP DATABASE IF EXISTS ``;'
out: ERROR 1102 (42000) at line 1: Incorrect database name ''
```

fix for drush 9 database name parsing

---

util/remove_old_builds.sh

Tiny fix related to https://github.com/codeenigma/deployments/issues/22
Add a switch to the find command that looks for old builds to remove, the switch lets the find command follow symlinks. This solves the problem where `/var/www` is a symlink to somewhere else, whilst not causing problems where `/var/www` is an absolute path.

remove_old_builds: follow symlink when searching for builds

---

common/ConfigFile.py
common/Tests.py
drupal/DrupalTests.py
drupal/fabfile.py

Adding CodeSniffer support, which closes #102, and also making a small start on #22 by introducing the 'www-root' param to the run_tests() function.

CodeSniffer support

---

drupal/fabfile.py

This is so the correct PHP config is used during the `composer install` step.

Wrap the composer install function in a with shell_env() clause

---

drupal/DrupalUtils.py

It shouldn't need a 'site' passing.

Fixing bug in determine_drupal_version

---

common/Tests.py
drupal/fabfile.py

This allows Drupal users to set a regex check to assure themselves a build succeeded. It runs at the end of the tests section and optionally sends an email too. You may pass it cURL options, by default it uses -sL (silent and follow redirects).

Fixes #219, adding a regex check

---

common/Utils.py
drupal/fabfile.py

Fixes #251 by ensuring we're in the previous directory, after checking the symlink exists. Then, return the output of `pwd -P` rather than reading the actual symlink.

Update previous build fetch

---

drupal/fabfile.py

Although we're going to iterate over the mapping dictionary, the sites_deployed dictionary is still used should a failure occur during PHP unit tests.

Run tests for all sites in mapping, not just the existing ones.

---

common/Utils.py
drupal/fabfile.py

First attempt at doing this, which could be improved in the future, potentially. This is so we can use build hooks on multisite setups. In our case, stage_file_proxy needs to be enabled on each site in the setup in a post-build hook, but as we weren't passing the site name to the build hooks, it was not possible.
I've done it this way so already existing build hooks won't break (at least, they _shouldn't_ break). The build_hook_version will default to **1**. Multisite clients who want to use build hooks will need to set that to **2** in their config.ini file.

Allow different build hook versions

---

drupal/fabfile.py

Actually use the site variable that is passed to the test_runner.

Don't set the site to None during a post-test build hook call

---

drupal/fabfile.py

When a feature branch build uses the production site to grab a database from, the `env.host` variable is set to the production host. The variable is then left untouched, so when the URL is created for the feature branch site, it's using the production host rather than the development host, which is incorrect.
This change will ensure the env.host variable is reset to the correct value, as the env.roledefs is populated **before** the database is fetched.

Reset env.host after fetching a database dump

---

common/Utils.py
drupal/fabfile.py

It would be handy to be able to override the `fullpath` variable in the `read_config_file()` function, without having to fork the repo and edit the ConfigFile.py script.
`config_fullpath` with default to `False`. Because the variables from the `fab` command are passed through as strings, I've added a check at the top to convert it to a boolean, to work with the config functions.

Config fullpath override and some debug info

---

drupal/Drupal.py
drupal/DrupalConfig.py
drupal/DrupalTests.py
drupal/FeatureBranches.py
drupal/InitialBuild.py
drupal/fabfile.py

Fixes #162 by providing the ability to use CMI Tools for config management by setting a value in config.ini.
It needs to be included in composer.json or directly committed (whichever method is used in the project) and the following added to the correct config.ini file, under the [Drupal] section:
```
import_config_method=cimy
default_cimy_source=../config/sync/default
site1_cimy_source=../config/sync/site1
```
The above example is for a multisite setup where the sites in `sites/default` and `sites/site1` are being built. Those are the **required** options. There are also optional options:
```
default_cimy_delete=../drush/config-delete-default.yml
default_cimy_install=../config_install_default/
```
The default values for those two options are `../drush/config-delete.yml` and …

Adding ability to use CMI Tools for config management

---

flat/fabfile.py

The pre-build hooks are currently called before the repo is cloned on the target, thus failing.

Fix order of repo cloning to allow pre-build hooks to run

---

drupal/FeatureBranches.py
drupal/fabfile-teardown.py

We provide the ability to set a fullpath (path override, effectively) for the config.ini file when deploying a site (or feature branch site), but we don't have this ability when tearing the build down. If a feature branch is built using a config.ini override path, it can't be torn down with Jenkins because Jenkins will use the wrong config.ini file.

config.ini override for FB teardowns

---

drupal/Drupal.py
drupal/DrupalUtils.py
drupal/Multisite.py
drupal/Sync.py

We're seeing issues with drush 9 and the deployment scripts (specifically regarding sql-dump), that cause feature branch builds to fail.
The issue occurs because in drush 9 `drush sql-dump` no longer dumps to stdout by default, rather it dumps to an arbitrary file (who thought this was a good idea!?).
( https://github.com/drush-ops/drush/issues/3364 is related)
My suggested fix is to append `--result-file=/dev/stdout` too all occurences of sql-dump in the scripts. The nice thing about doing it this way is it retains compatibility with older versions of drush.
This PR should supercede https://github.com/codeenigma/deployments/pull/248

Drush 9 compatibility

---

common/PHP.py
common/Utils.py
drupal/fabfile-editorial.py
drupal/fabfile.py
symfony/fabfile.py

Did some basic tests with the pre-prim step and it appears to work fine.
Editorial builds needed to remove old builds, so they now do upon successful completion of a deployment.
The pre-hook step was being called **before** the Symfony repo was cloned down, so the pre hooks never fired because Jenkins could not find them. I've moved the clone_repo call so it runs before pre hooks are run.

Primary server build hooks and other small changes

---

drupal/AdjustConfiguration.py
drupal/Drupal.py
drupal/Revert.py
drupal/fabfile.py

Various changes included in this:
1. Repositioning the database backup call so it happens **after** the site is taken offline. As a result, I've had to add a function to Revert.py to bring the site back online after a revert happens.
2. Reintroduce the ability to pass in `do_updates` via the Jenkins job. I don't think this should be handled in config.ini (or prod.config.ini for production sites), as it would be far more convenient to do this at the time of running a prod build.
With this, however, a database backup will still be taken even though the site is not taken offline. Pretty edge case, though. Perhaps a discussion with our client in question needs to be had to encourage them to use readonly mode instead. But, this change, ideally, needs to go through before that conversation …

Various changes

---

drupal/DrupalUtils.py
drupal/fabfile-databasedump.py

This is done by not relying on Drush aliases to get a database dump. The aliases used by Drush 8 do not work with Drush 9. \o/

Fixing get_database() function in DrupalUtils

---

common/GenericSync.py
common/MySQL.py
common/fabfile-genericsync.py

Also accidentally committed the GenericSync stuff I was working on way back when, but I don't think that's an issue. Might as well keep in place.

Remove DEFINER statements from database backup when reverting a build.

---

drupal/FeatureBranches.py
drupal/fabfile-teardown.py

Workaround for when feature branches use a remote database, which prevented them from being torn down.

Feature branch teardown when using remote DB

---

drupal/Drupal.py
drupal/FeatureBranches.py

Currently, if MySQL is set to anything but 5.5 in the config.ini file, feature branch teardowns have a chance of failing due to how we currently drop the database and database user.
At times, if the branch in use has a long name, the database username will differ from the database name, which causes issues when trying to remove the database user. This PR fixes that, along with a long-standing issue whereby a feature branch build can't be removed if the database can't be bootstrapped.

Feature branch teardown fix

---

common/BuildTeardown.py

This way, if two branches have very similar names, such as `fb_test` and `fb_testv2`, tearing down the former won't remove the latter's vhost, which is what was happening.

Append a / when searching for the root in a vhost during teardowns.

---

drupal/InitialBuild.py

Drupal 8.8 uses a different variable for the config directory, so we need to add that to settings.php during an initial build.

Add support for Drupal 8.8

---

common/Tests.py
drupal/Drupal.py
drupal/fabfile.py

Currently, if a project installs phpunit in their main composer.json file and they want to run phpunit tests, it causes an issue as the scripts try to install phpunit again. So I'm introducing an option which can be used to disable that.

Post-online cache clears and phpunit

---

drupal/Sync.py
drupal/fabfile-sync.py

Some Drupal syncs take ages because we're forcing the use of `drush sql-cli`. This PR provides the ability to use `mysql` instead by setting a parameter in the Jenkins job.

Drupal syncs
